networks:
  skeletonbr:
    driver: bridge

services:
  php:
    container_name: 'php-skeleton'
    networks:
      - skeletonbr
    build:
      context: ./docker/php
    volumes:
      - '.:/var/www/html'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
    working_dir: '/var/www/html'
    extra_hosts:
    # for step debugging with Xdebug
      - 'host.docker.internal:host-gateway'

  nginx:
    container_name: 'nginx-skeleton'
    platform: linux/x86_64
    image: nginx:1.23.2-alpine
    networks:
      - skeletonbr
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf'

  database:
    container_name: 'mysql-skeleton'
    platform: linux/x86_64
    image: mysql:5.7.40
    networks:
      - skeletonbr
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'guestbook'
      MYSQL_USER: 'chester'
      MYSQL_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin
    networks:
      - skeletonbr
    ports:
      - '8080:80'  # You can access phpMyAdmin at http://localhost:8080
    environment:
      PMA_HOST: database
      PMA_USER: chester
      PMA_PASSWORD: root
    depends_on:
      - database

volumes:
  mysql_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
